import { PlanConfig, PlanTier } from "@/modules/entitlement/types";

export const PLANS_CONFIG: Record<PlanTier, PlanConfig> = {
    free: {
        name: "Free",
        description: "For individuals and small setups to explore Qrezo core features.",
        tier: "free",
        limits: {
            qr_codes: 3,
            smart_pages: 1,
            events: 1,
            attendees: 50,
            scanner_devices: 1,
            api_keys: 0,
            webhook_endpoints: 0,
            notification_templates: 1,
            workspaces: 1,
        },
        features: {
            custom_branding: false,
            api_access: false,
            webhooks: false,
            notifications: false,
            custom_domain: false,
            advanced_analytics: false,
            qrezo_connect: false,
        },
    },
    pro: {
        name: "Pro",
        description: "For creators, event managers, and growing businesses.",
        tier: "pro",
        limits: {
            qr_codes: 50,
            smart_pages: 10,
            events: 5,
            attendees: 500,
            scanner_devices: 3,
            api_keys: 2,
            webhook_endpoints: 2,
            notification_templates: 5,
            workspaces: 3,
        },
        features: {
            custom_branding: true,
            api_access: true,
            webhooks: true,
            notifications: true,
            custom_domain: false,
            advanced_analytics: true,
            qrezo_connect: false,
        },
    },
    business: {
        name: "Business",
        description: "For agencies, teams, and high-volume event platforms.",
        tier: "business",
        limits: {
            qr_codes: 1000,
            smart_pages: 100,
            events: 50,
            attendees: 10000,
            scanner_devices: 20,
            api_keys: 10,
            webhook_endpoints: 10,
            notification_templates: 25,
            workspaces: 10,
        },
        features: {
            custom_branding: true,
            api_access: true,
            webhooks: true,
            notifications: true,
            custom_domain: true,
            advanced_analytics: true,
            qrezo_connect: true,
        },
    },
    enterprise: {
        name: "Enterprise",
        description: "Reserved for custom contracts and enterprise organizations.",
        tier: "enterprise",
        limits: {
            qr_codes: 1000000,
            smart_pages: 1000,
            events: 500,
            attendees: 100000,
            scanner_devices: 100,
            api_keys: 50,
            webhook_endpoints: 50,
            notification_templates: 100,
            workspaces: 50,
        },
        features: {
            custom_branding: true,
            api_access: true,
            webhooks: true,
            notifications: true,
            custom_domain: true,
            advanced_analytics: true,
            qrezo_connect: true,
        },
    },
};
